#!/bin/bash
# Create dae file, ikfast code, moveit plugin

. $ROS_ROOT/../rosbash/rosbash
die() { echo "Error $*. Exit."; exit 1; }
roscd lmtclam || die "roscd"
cd ikfast || die "cd"

FN=_gen_clam
R=5  # rounding digits

# Taken from http://wiki.ros.org/Industrial/Tutorials/Create_a_Fast_IK_Solution
# See also http://wiki.ros.org/Industrial/Tutorials/Create_a_Fast_IK_Solution/arm_navigation_plugin
# http://docs.ros.org/hydro/api/moveit_ikfast/html/doc/ikfast_tutorial.html

rosrun xacro xacro.py ../model/clam.xacro tool:=none > $FN.urdf || die xacro

rosrun collada_urdf urdf_to_collada $FN.urdf $FN.dae || die urdf_to_collada
# Crashes with pen tool!

# Round translations and rotaion axes to $R, angles to 0. Updated script!
rosrun moveit_ikfast round_collada_numbers.py $FN.dae $FN.round$R.dae $R $R 0 || die rounding
# rosrun lmtclam round_collada_numbers_copy.py $FN.dae $FN.round$R.dae $R $R 0

openrave-robot.py $FN.dae --info links
openrave-robot.py $FN.dae --info joints

/usr/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py --robot=$FN.round$R.dae --iktype=transform6d --baselink=0 --eelink=8 --freeindex=2 --savefile=_gen_ikfast61.round$R.cpp -d 9 || die "generating ikfast"

g++ -lstdc++ -llapack -o ik_test _gen_ikfast61.round$R.cpp || die "compiling ikfast"

# The package lmtclam_moveit_config is generated by the GUI:
# roslaunch moveit_setup_assistant setup_assistant.launch

# IKFast Moveit plugin
rosrun moveit_ikfast create_ikfast_moveit_plugin.py lmtclam arm lmtclam_moveit_ikfast _gen_ikfast61.round$R.cpp || die "create_ikfast_moveit_plugin"

# Test of FastIK
openrave.py --database inversekinematics --robot=clam.robot.xml --iktests=1000
openrave.py --database inversekinematics --robot=clam.robot.xml --show